# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backprop <- function(n_hidden, w_ini, x, y, w, valid, x_valid, y_valid, w_valid, activate, activate_, n_epoch, n_batch, model_type, learning_rate, l1_reg, l2_reg, early_stop_det) {
    .Call(`_dnnet_backprop`, n_hidden, w_ini, x, y, w, valid, x_valid, y_valid, w_valid, activate, activate_, n_epoch, n_batch, model_type, learning_rate, l1_reg, l2_reg, early_stop_det)
}

